version: '3.8'

services:
  bep:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  # Usługa bazy danych MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pokerDB
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    ports:
      - "3307:3306"

volumes:
  db_data:

